#!/bin/bash
# Dream Team Session Initialization
# Creates required directory structure for spelunk docs and worktrees

# Create spelunk documentation directories if they don't exist
mkdir -p docs/spelunk/{contracts,flows,boundaries,trust-zones}

# Create spelunk index if it doesn't exist
if [ ! -f docs/spelunk/_index.md ]; then
  cat > docs/spelunk/_index.md << 'INDEXEOF'
# Spelunk Documentation Index

## Contracts
Type definitions, API signatures, validation schemas.

## Flows
User-facing entry points, request flows, state transitions.

## Boundaries
Module import/export maps, dependency directions, coupling analysis.

## Trust Zones
Auth checks, data sanitization points, privilege boundaries.

---
*Auto-generated by Dream Team plugin. Updated as agents spelunk the codebase.*
INDEXEOF
fi

# Create staleness tracking file if it doesn't exist
if [ ! -f docs/spelunk/_staleness.json ]; then
  echo '{}' > docs/spelunk/_staleness.json
fi

# Create docs plan directories
mkdir -p docs/plans/{architect,product,design}
mkdir -p docs/plans/architect/drift-resolutions
mkdir -p docs/features

# Create worktrees directory (sibling to project root)
WORKTREE_DIR="../worktrees"
if [ ! -d "$WORKTREE_DIR" ]; then
  mkdir -p "$WORKTREE_DIR"
fi

# Add dtq CLI to PATH if installed
DTQ_DIR="${CLAUDE_PLUGIN_ROOT}/../tools/dtq"
DTQ_BIN="${DTQ_DIR}/dtq"
if [ -f "$DTQ_BIN" ]; then
  export PATH="${DTQ_DIR}:${PATH}"
fi

echo "Dream Team session initialized."
